#!/usr/bin/env php
<?php
/**
 * Flitch
 *
 * @link      http://github.com/DASPRiD/Flitch For the canonical source repository
 * @copyright 2011-2012 Ben Scholzen 'DASPRiD'
 * @license   http://opensource.org/licenses/BSD-2-Clause Simplified BSD License
 */

require_once __DIR__ . '/src/autoload_register.php';

$cli = new Flitch\Cli\Cli(getcwd());
$cli->run(isset($_SERVER['argv']) ? $_SERVER['argv'] : array());
