#!/usr/bin/env php
<?php
/**
 * PHPCV
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to mail@dasprids.de so I can send you a copy immediately.
 *
 * @category   PHPCV
 * @copyright  Copyright (c) 2011 Ben Scholzen <mail@dasprids.de>
 * @license    New BSD License
 */

require_once __DIR__ . '/src/autoload_register.php';

$cli = new PHPCV\Cli\Cli(getcwd());
$cli->run(isset($_SERVER['argv']) ? $_SERVER['argv'] : array());
