<?php
/**
 * Flitch
 *
 * @link      http://github.com/DASPRiD/Flitch For the canonical source repository
 * @copyright 2011-2012 Ben DASPRiD Scholzen
 * @license   http://opensource.org/licenses/BSD-2-Clause Simplified BSD License
 */

// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Flitch\Report\Report'                        => __DIR__ . '//Flitch/Report/Report.php',
    'Flitch\Report\Checkstyle'                    => __DIR__ . '//Flitch/Report/Checkstyle.php',
    'Flitch\Report\Cli'                           => __DIR__ . '//Flitch/Report/Cli.php',
    'Flitch\Exception\OutOfBoundsException'       => __DIR__ . '//Flitch/Exception/OutOfBoundsException.php',
    'Flitch\Exception\RuntimeException'           => __DIR__ . '//Flitch/Exception/RuntimeException.php',
    'Flitch\Version'                              => __DIR__ . '//Flitch/Version.php',
    'Flitch\Rule\Rule'                            => __DIR__ . '//Flitch/Rule/Rule.php',
    'Flitch\Rule\Line\Separator'                  => __DIR__ . '//Flitch/Rule/Line/Separator.php',
    'Flitch\Rule\Line\DisallowTrailingWhitespace' => __DIR__ . '//Flitch/Rule/Line/DisallowTrailingWhitespace.php',
    'Flitch\Rule\Line\MaxLength'                  => __DIR__ . '//Flitch/Rule/Line/MaxLength.php',
    'Flitch\Rule\Naming\Constants'                => __DIR__ . '//Flitch/Rule/Naming/Constants.php',
    'Flitch\Rule\Naming\Classes'                  => __DIR__ . '//Flitch/Rule/Naming/Classes.php',
    'Flitch\Rule\Naming\Methods'                  => __DIR__ . '//Flitch/Rule/Naming/Methods.php',
    'Flitch\Rule\AbstractRule'                    => __DIR__ . '//Flitch/Rule/AbstractRule.php',
    'Flitch\Rule\File\DisallowShortOpenTags'      => __DIR__ . '//Flitch/Rule/File/DisallowShortOpenTags.php',
    'Flitch\Rule\File\MustStartWithOpenTag'       => __DIR__ . '//Flitch/Rule/File/MustStartWithOpenTag.php',
    'Flitch\Rule\Manager'                         => __DIR__ . '//Flitch/Rule/Manager.php',
    'Flitch\Rule\Loader'                          => __DIR__ . '//Flitch/Rule/Loader.php',
    'Flitch\Rule\Whitespace\DisallowTabulators'   => __DIR__ . '//Flitch/Rule/Whitespace/DisallowTabulators.php',
    'Flitch\Rule\Whitespace\Indentation'          => __DIR__ . '//Flitch/Rule/Whitespace/Indentation.php',
    'Flitch\Test\RuleTestCase'                    => __DIR__ . '//Flitch/Test/RuleTestCase.php',
    'Flitch\File\Violation'                       => __DIR__ . '//Flitch/File/Violation.php',
    'Flitch\File\File'                            => __DIR__ . '//Flitch/File/File.php',
    'Flitch\File\Tokenizer'                       => __DIR__ . '//Flitch/File/Tokenizer.php',
    'Flitch\File\Token'                           => __DIR__ . '//Flitch/File/Token.php',
    'Flitch\Cli\ArgumentParser'                   => __DIR__ . '//Flitch/Cli/ArgumentParser.php',
    'Flitch\Cli\Cli'                              => __DIR__ . '//Flitch/Cli/Cli.php',
    'Flitch\Exception'                            => __DIR__ . '//Flitch/Exception.php',
);
